export const EMAIL_LOGIN_SUCCESS = 'EMAIL_LOGIN_SUCCESS';
export const EMAIL_LOGIN_FAIL = 'EMAIL_LOGIN_FAIL';
export const LOG_OUT = 'LOG_OUT';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const ADD_USER_INFORMATION = 'ADD_USER_INFORMATION';
export const REMOVE_USER_INFORMATION = 'REMOVE_USER_INFORMATION';
